// <auto-generated />
using KiralamaProjesi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KiralamaProjesi.Migrations
{
    [DbContext(typeof(KiralamaDbContext))]
    [Migration("20181216200209_initalcreate")]
    partial class initalcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KiralamaProjesi.Models.Araba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("Bagaj");

                    b.Property<int>("Fiyat");

                    b.Property<string>("Guvenlik");

                    b.Property<string>("KisiSayisi");

                    b.Property<string>("KmSiniri");

                    b.Property<int>("MarkaId");

                    b.Property<string>("Picture");

                    b.Property<string>("YasSiniri");

                    b.HasKey("Id");

                    b.HasIndex("MarkaId");

                    b.ToTable("Arabalar");
                });

            modelBuilder.Entity("KiralamaProjesi.Models.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("Description");

                    b.Property<string>("Picture");

                    b.HasKey("Id");

                    b.ToTable("Markalar");
                });

            modelBuilder.Entity("KiralamaProjesi.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("Adres");

                    b.Property<int>("ArabaId");

                    b.Property<string>("Cvv");

                    b.Property<string>("Email");

                    b.Property<string>("KrediAd");

                    b.Property<string>("Kredino");

                    b.Property<string>("OdemeTipi");

                    b.Property<string>("PostaKodu");

                    b.Property<string>("Sehir");

                    b.Property<string>("Soyad");

                    b.Property<string>("Telefon");

                    b.Property<string>("Ulke");

                    b.HasKey("Id");

                    b.HasIndex("ArabaId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("KiralamaProjesi.Models.Araba", b =>
                {
                    b.HasOne("KiralamaProjesi.Models.Marka", "Marka")
                        .WithMany("Arabalar")
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KiralamaProjesi.Models.Musteri", b =>
                {
                    b.HasOne("KiralamaProjesi.Models.Araba", "Araba")
                        .WithMany("Musteriler")
                        .HasForeignKey("ArabaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
